"""Shared helpers for the solve and grading task materializers.

Materialization is paths-in, files-out and byte-deterministic: no
timestamps, absolute paths, or machine-specific content ever enters a
task directory (docs/design.md, implementation rules).
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import stat
from pathlib import Path

from ..hashing import file_manifest

GENERATED_MARKER = "# --- generated by agentic-assessment-toolkit ---"

_SLUG_PATTERN = re.compile(r"[^A-Za-z0-9._-]+")


class MaterializeError(Exception):
    """A task cannot be materialized from the given inputs."""


def slugify(text: str) -> str:
    slug = _SLUG_PATTERN.sub("-", text).strip("-")
    return slug or "x"


def task_dir_name(parts: list[str], item_id: str) -> str:
    """Deterministic, filesystem-safe task directory name.

    The trailing hash of the exact item id keeps names unique even when
    slugification collapses distinct raw names.
    """
    suffix = hashlib.sha256(item_id.encode("utf-8")).hexdigest()[:8]
    return "__".join([*(slugify(part) for part in parts), suffix])


def create_task_dir(tasks_dir: Path, name: str) -> Path:
    task_dir = tasks_dir / name
    if task_dir.exists():
        raise MaterializeError(f"task directory already exists: {task_dir}")
    task_dir.mkdir(parents=True)
    return task_dir


def copy_tree(source: Path, destination: Path) -> None:
    if not source.is_dir():
        raise MaterializeError(f"not a directory: {source}")
    shutil.copytree(source, destination)


def write_dockerfile(task_dir: Path, template_bytes: bytes, copy_lines: list[str]) -> None:
    """Write environment/Dockerfile: the flavor template plus generated COPYs.

    Harbor's Docker build context is the task's environment/ directory,
    so content presented to the agent under /app must be copied into the
    image from there.
    """
    environment_dir = task_dir / "environment"
    environment_dir.mkdir(parents=True, exist_ok=True)
    tail = "\n".join([GENERATED_MARKER, *copy_lines])
    text = template_bytes.decode("utf-8").rstrip("\n") + "\n\n" + tail + "\n"
    (environment_dir / "Dockerfile").write_text(text, encoding="utf-8")


def write_test_runner(task_dir: Path, verifier_filename: str) -> None:
    tests_dir = task_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    script = tests_dir / "test.sh"
    script.write_text(
        "#!/bin/sh\n"
        "# Generated by agentic-assessment-toolkit: run the generic contract verifier.\n"
        "set -eu\n"
        f"exec python3 /tests/{verifier_filename}\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def write_input_manifest(task_dir: Path, inputs_dir: Path) -> None:
    manifest = file_manifest(inputs_dir)
    (task_dir / "tests" / "input_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
